version: "3.8"
services:
  db:
    image: mariadb:latest
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
    ports:
      - 13306:3306
volumes:
  db-store: {}
